[theme]
primaryColor = "#0F3250"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#E7F1F4"
textColor = "#19364D"
font = "sans serif"

[server]
address = "127.0.0.1"
maxUploadSize = 50
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
